openapi: 3.0.2
info:
    title: Weather adapter API
    version: 1.0.0
    description: Adapter for communicating with an external weather API
paths:
    /adapter/weather:
        get:
            parameters:
                - name: city
                  description: Name of the city to search for
                  schema:
                      type: string
                  in: query
                  required: true
            responses:
                '200':
                    description: Successfully retrieved weather data
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/WeatherDto'
                '400':
                    description: Bad request (e.g. parameter is missing)
                '502':
                    description: Error communicating with the external API
            summary: Get raw weather data from the external API
components:
    schemas:
        WeatherDto:
            type: object
            properties:
                city:
                    type: string
                temperature:
                    type: number
                    format: double
                description:
                    type: string
