spring.application.name=weather-adapter
server.port=${SERVER_PORT:8081}

adapter.external.base-url=${ADAPTER_EXTERNAL_BASE_URL:https://api.openweathermap.org}
adapter.external.api-key=${ADAPTER_EXTERNAL_API_KEY:68b5417b7e7860f81645a747ce6a521a}
adapter.resilience.retry.max-attempts=${ADAPTER_RETRY_MAX_ATTEMPTS:3}
adapter.resilience.retry.wait-duration=${ADAPTER_RETRY_WAIT_DURATION:200ms}
adapter.resilience.circuit-breaker.failure-rate-threshold=${ADAPTER_CB_FAILURE_RATE_THRESHOLD:50}
adapter.resilience.circuit-breaker.sliding-window-size=${ADAPTER_CB_SLIDING_WINDOW_SIZE:4}
adapter.resilience.circuit-breaker.minimum-number-of-calls=${ADAPTER_CB_MINIMUM_NUMBER_OF_CALLS:4}
adapter.resilience.circuit-breaker.wait-duration-open-state=${ADAPTER_CB_WAIT_DURATION_OPEN_STATE:30s}
adapter.resilience.circuit-breaker.permitted-calls-in-half-open-state=${ADAPTER_CB_PERMITTED_CALLS_HALF_OPEN:1}